include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.gen.dart
    - lib/**.gr.dart
    - lib/**.freezed.dart
    - lib/**.config.dart
  errors:
    prefer_relative_imports: warning
    cancel_subscriptions: warning
    missing_return: error
    missing_required_param: error
    parameter_assignments: error
    always_use_package_imports: ignore
    invalid_annotation_target: ignore
    avoid_dynamic_calls: ignore
    avoid_positional_boolean_parameters: ignore
    body_might_complete_normally_nullable : ignore
    use_key_in_widget_constructors: ignore
    depend_on_referenced_packages: ignore

linter:
  rules:
    prefer_relative_imports: true
    cancel_subscriptions: true