name: trakt
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_debounce: ^2.0.2+1
  fading_edge_scrollview: ^2.0.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.0.3
  geolocator: ^8.2.1
  get_it: ^7.2.0
  google_fonts: ^2.3.3
  injectable: ^1.5.3
  logger: ^1.1.0
  mapbox_gl: ^0.16.0
  modal_bottom_sheet: ^2.0.1
  permission_handler: ^9.2.0
  rxdart: ^0.27.3

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.1.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  pmobi_mwwm:
    git: https://git.pmobi.tech/plugins/pmobi_mwwm.git

flutter_gen:
  output: lib/generated/

flutter:
  uses-material-design: true
  assets:
    - assets/cache.db
    - .env
